import random
print("Choose a template:")
print("1. Hospital Story")
print("2. Camping Story")
print("3. Castle Story")
n = input("1, 2, 3: ")
if (n == '1'):
    Number = input("Number: ")
    Measure_of_time = input("Measure_of_time: ")
    Mode_of_Transportation = input("Mode_of_Transportation: ")
    Adjective = input("Adjective: ")
    Adjective2 = input("Adjective2: ")
    Noun = input("Noun: ")
    Color = input("Color: ")
    Part_of_the_Body = input("Part_of_the_Body: ")
    Verb = input("Verb: ")
    Number2 = input("Number2: ")
    Noun2 = input("Noun2: ")
    Noun3 = input("Noun3: ")
    Part_of_the_Body_2 = input("Part_of_the_Body_2: ")
    Noun4 = input("Noun4: ")
    Adjective3 = input("Adjective3: ")
    Silly_Word = input("Silly_Word: ")
    print("It was about", Number, Measure_of_time, " ago when I arrived at the hospital in a ", Mode_of_Transportation, ". ")
    print("The hospital is a/an ", Adjective, " place, there are a lot of ", Adjective2, Noun, " here. ")
    print("There are nurses here who have ", Color, Part_of_the_Body ,".")
    print("If someone wants to come into my room I told them that they have to ", Verb," first.") 
    print("I've decorated my room with ", Number2, Noun2, ".")
    print("Today I talked to a doctor and they were wearing a ", Noun3, " on their ", Part_of_the_Body_2, ".")
    print("I heard that all doctors ", Verb, Noun4, " every day for breakfast. ")
    print("The most ", Adjective3, " thing about being in the hospital is the ", Silly_Word, Noun, "!")
    
elif (n == '2'):
    Proper_Noun = input("Person’s Name: ")
    Noun = input("Noun: ")
    Adjective = input("Feeling: ")
    Adjective2 = input("Feeling2: ") 
    Animal = input("Animal: ")
    Verb2 = input("Verb2: ")
    Color = input("Color: ")
    Verb = input("Verb: ") 
    Adverb = input("Adverb: ")
    Number = input("Number: ")
    Measure_of_Time = input("Measure_of_Time: ")
    Silly_Word = input("Silly_Word: ")
    Noun2 = input("Noun2: ")
    print("This weekend I am going camping with ", Proper_Noun, ".")
    print("I packed my lantern, sleeping bag, and ", Noun, ".")
    print("I am so ", Adjective, "to ", Verb,  " in a tent. ")
    print("I am ", Adjective2, "we might see a(n) ", Animal, ", I hear they’re kind of dangerous.")
    print("While we’re camping, we are going to hike, fish, and ", Verb2, ".")
    print("I have heard that the ", Color," lake is great for ", Verb+"ing", ".")
    print("Then we will ", Adverb+"ly", " hike through the forest for ", Number,  Measure_of_Time, ".")
    print("If I see a ", Color , Animal,  " while hiking, I am going to bring it home as a pet! ")
    print("At night we will tell ", Number, Silly_Word, " stories and roast ", Noun2, " around the campfire!!")
    
elif (n == '3'):
    Proper_Noun = input("Person’s Name: ")
    Adjective = input("Adjective: ")
    Color = input("Color: ")
    Animal = input("Animal: ")
    Place = input("Place: ")
    Adjective2 = input("Adjective2: ")
    Magical_Creature = input("Plural: ")
    Adjective3 = input("Adjective3: ")
    Magical_Creature2 = input("Plural: ")
    Room_in_a_House = input("Romm_in_a_House: ")
    Noun = input("Noun: ")
    Noun2 = input("Noun2: ")
    Noun3 = input("Plural: ")
    Adjective4 = input("Adjective4: ")
    Noun4 = input("Plural: ")
    Number = input("Number: ")
    Measure_of_time = input("Measure_of_time" )
    Verb = input("Verb: ")
    Adjective5 = input("Adjective5: ")
    Noun5 = input("Plural: ")
    print("Dear ",Proper_Noun, ", I am writing to you from a ", Adjective," castle in an enchanted forest. ")
    print("I found myself here one day after going for a ride on a ",Color, Animal, " in ", Place, ". ")
    print("There are ",Adjective2, Magical_Creature," and ", Adjective3, Magical_Creature2," here! ")
    print("In the ", Room_in_a_House," there is a pool full of ", Noun, "." )
    print("I fall asleep each night on a ",Noun2," of ", Noun3, " and dream of ", Adjective4,  Noun4, ".")
    print("It feels as though I have lived here for ", Number, Measure_of_time, ".")
    print("I hope one day you can visit, although the only way to get here now is ",Verb+"in"," on a ",Adjective5, Noun5, "!!")
    
else:
    print("Invalid.")